package com.example.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendao.bean.OssDB;
import com.example.greendao.bean.PartDB;

import com.example.greendao.dao.OssDBDao;
import com.example.greendao.dao.PartDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ossDBDaoConfig;
    private final DaoConfig partDBDaoConfig;

    private final OssDBDao ossDBDao;
    private final PartDBDao partDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ossDBDaoConfig = daoConfigMap.get(OssDBDao.class).clone();
        ossDBDaoConfig.initIdentityScope(type);

        partDBDaoConfig = daoConfigMap.get(PartDBDao.class).clone();
        partDBDaoConfig.initIdentityScope(type);

        ossDBDao = new OssDBDao(ossDBDaoConfig, this);
        partDBDao = new PartDBDao(partDBDaoConfig, this);

        registerDao(OssDB.class, ossDBDao);
        registerDao(PartDB.class, partDBDao);
    }
    
    public void clear() {
        ossDBDaoConfig.clearIdentityScope();
        partDBDaoConfig.clearIdentityScope();
    }

    public OssDBDao getOssDBDao() {
        return ossDBDao;
    }

    public PartDBDao getPartDBDao() {
        return partDBDao;
    }

}
